# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0rrilmiahkljg8cvaqafz90fg3561zibh0b2ffdqnjkf10qansky";
    aarch64-linux = "1bxir4ykyznk3ki2yipn0rb0jb3y4chkkii9h253ggraisilg8f5";
    x86_64-darwin = "1a6hz923ggbwraafydmqfh3fb7k2a5ri1l8i9z8s6kk0lbbj011p";
    aarch64-darwin = "1wq1kq2zkdpx4wzsvd7dhc2d3s45mi274n26whp6yb28z3j10fb9";
  };

  urlMap = {
    x86_64-linux = "https://o.xdb.be/hammer/release/v0.0.4/hammer_Linux_x86_64.tar.gz";
    aarch64-linux = "https://o.xdb.be/hammer/release/v0.0.4/hammer_Linux_arm64.tar.gz";
    x86_64-darwin = "https://o.xdb.be/hammer/release/v0.0.4/hammer_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://o.xdb.be/hammer/release/v0.0.4/hammer_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "hammer";
  version = "0.0.4";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./hammer $out/bin/hammer
  '';

  system = system;

  meta = {

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
